image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - push
  - test

before_script:
  - docker info
  - export ANSIBLE_VERSION="$(grep ansible_version= Dockerfile | awk -F'=' '{print $2}')"

build:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build -t $CI_COMMIT_SHORT_SHA:$CI_COMMIT_SHA -t $CI_COMMIT_SHORT_SHA:$ANSIBLE_VERSION .
    - docker images
    - docker run --rm $CI_COMMIT_SHORT_SHA:$CI_COMMIT_SHA ansible --version
    - docker run --rm $CI_COMMIT_SHORT_SHA:$CI_COMMIT_SHA molecule --version

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker build -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION .
   - docker images
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION

test_docker_images:
 stage: test
 only:
   - master
 script:
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION molecule --version
