image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - push
  - test

before_script:
  - docker info
  - export ANSIBLE_VERSION="$(grep ansible_version= Dockerfile | awk -F'=' '{print $2}')"

build:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    # build the latest image
    - docker build -f Dockerfile -t $CI_COMMIT_SHORT_SHA:latest .
    - docker images
    - docker run --rm $CI_COMMIT_SHORT_SHA:latest ansible --version
    - docker run --rm $CI_COMMIT_SHORT_SHA:latest molecule --version
    # build image with root user
    - docker build -f Dockerfile-root -t $CI_COMMIT_SHORT_SHA:root .
    - docker images
    - docker run --rm $CI_COMMIT_SHORT_SHA:root ansible --version
    - docker run --rm $CI_COMMIT_SHORT_SHA:root molecule --version


push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker build -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION .
   - docker build -f Dockerfile-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-root .
   - docker images
   # test latest image before push
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
   # test root image before push
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root molecule --version
   # push latest image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION
   # push root image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-root

test_docker_images:
 stage: test
 only:
   - master
 script:
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION molecule --version
