 image: docker:stable

 variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2

 services:
   - docker:dind

 stages:
   #- build
   - push

 before_script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD # $CI_REGISTRY_DOMAIN
   - docker info

 #build:
 #  stage: build
 #  script:
 #   # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
 #    - docker build -t $CI_REGISTRY_DOMAIN/$CI_REGISTRY_USER/$CI_REGISTRY_PROJECT:latest -t $CI_REGISTRY_DOMAIN/$CI_REGISTRY_USER/$CI_REGISTRY_PROJECT:$CI_COMMIT_SHA .

 push:
  stage: push
  only:
    - master
  script:
    - docker build -t $CI_REGISTRY_DOMAIN/$CI_REGISTRY_USER/$CI_REGISTRY_PROJECT:latest -t $CI_REGISTRY_DOMAIN/$CI_REGISTRY_USER/$CI_REGISTRY_PROJECT:$CI_COMMIT_SHA .
    - docker images
    - docker push $CI_REGISTRY_DOMAIN/$CI_REGISTRY_USER/$CI_REGISTRY_PROJECT:latest
    - docker push $CI_REGISTRY_DOMAIN/$CI_REGISTRY_USER/$CI_REGISTRY_PROJECT:$CI_COMMIT_SHA
