image: docker:20.10

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10-dind

stages:
  - build
  - push
  - test

before_script:
  - docker info
  - export ANSIBLE_VERSION_210="$(grep ansible_version= Dockerfile-2.10 | awk -F'=' '{print $2}')"
  - export ANSIBLE_VERSION_29="$(grep ansible_version= Dockerfile | awk -F'=' '{print $2}')"
  - export ANSIBLE_VERSION_28="$(grep ansible_version= Dockerfile-2.8 | awk -F'=' '{print $2}')"
  - export ANSIBLE_VERSION_27="$(grep ansible_version= Dockerfile-2.7 | awk -F'=' '{print $2}')"

build:
  stage: build
  script:
   # ans 2.10
   - docker build -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.10 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_210 .
   # ans 2.9
   - docker build -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.9 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_29 .
   - docker build -f Dockerfile-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.9-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_29-root .
   # ans 2.8
   - docker build -f Dockerfile-2.8 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8 .
   - docker build -f Dockerfile-2.8-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8-root .
   # ans 2.7
   - docker build -f Dockerfile-2.7 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7 .
   - docker build -f Dockerfile-2.7-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7-root .
   # test 2.10
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_210 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_210 molecule --version
   # test 2.9
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root molecule --version
   # test 2.8
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root molecule --version
   # test 2.7
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root molecule --version
   # summary
   - docker images

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   # ans 2.10
   - docker build -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.10 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_210 .
   # ans 2.9
   - docker build -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.9 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_29 .
   - docker build -f Dockerfile-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.9-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_29-root .
   # ans 2.8
   - docker build -f Dockerfile-2.8 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8 .
   - docker build -f Dockerfile-2.8-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8-root .
   # ans 2.7
   - docker build -f Dockerfile-2.7 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7 .
   - docker build -f Dockerfile-2.7-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7-root .
   - docker images
   # test 2.10
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_210 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_210 molecule --version
   # test 2.9
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root molecule --version
   # test 2.8
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root molecule --version
   # test 2.7
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root molecule --version
   # summary
   - docker images
   # push 2.10 image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_210
   # push 2.9 image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_29
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.9
   # push 2.9 root image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_29-root
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.9-root
   # push 2.8 image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8
   # push 2.8 root image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8-root
   # push 2.7 image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7
   # push 2.7 root image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7-root

test_docker_images:
 stage: test
 only:
   - master
 script:
   # test 2.10
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_210 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_210 molecule --version
   # test 2.9
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root molecule --version
   # test 2.8
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root molecule --version
   # test 2.7
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root molecule --version
