image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - push
  - test

before_script:
  - docker info
  - export ANSIBLE_VERSION="$(grep ansible_version= Dockerfile | awk -F'=' '{print $2}')"
  - export ANSIBLE_VERSION-2.8="$(grep ansible_version= Dockerfile-2.8 | awk -F'=' '{print $2}')"
  - export ANSIBLE_VERSION-2.7="$(grep ansible_version= Dockerfile-2.7 | awk -F'=' '{print $2}')"

build:
  stage: build
  script:
   # ans 2.9
   - docker build -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION .
   - docker build -f Dockerfile-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-root .
   # ans 2.8
   - docker build -f Dockerfile-2.8 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8 .
   - docker build -f Dockerfile-2.8-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8-root .
   # ans 2.7
   - docker build -f Dockerfile-2.7 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7 .
   - docker build -f Dockerfile-2.7-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7-root .
   # test 2.9
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root molecule --version
   # test 2.8
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8 --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8-root molecule --version
   # test 2.7
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7 --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7-root molecule --version
   # summary
   - docker images

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   # ans 2.9
   - docker build -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION .
   - docker build -f Dockerfile-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-root .
   # ans 2.8
   - docker build -f Dockerfile-2.8 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8 .
   - docker build -f Dockerfile-2.8-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8-root .
   # ans 2.7
   - docker build -f Dockerfile-2.7 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7 .
   - docker build -f Dockerfile-2.7-root -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7-root .
   - docker images
   # test 2.9
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root molecule --version
   # test 2.8
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8 --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8-root molecule --version
   # test 2.7
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7 --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7-root molecule --version
   # summary
   - docker images
   # push latest image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION
   # push root image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-root

test_docker_images:
 stage: test
 only:
   - master
 script:
   # test 2.9
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root molecule --version
   # test 2.8
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8 --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.8-root molecule --version
   # test 2.7
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7 ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7 --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7-root ansible --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION-2.7-root molecule --version
   # summary
   - docker images
