---
services: docker

env:
  global:
    - DOCKERHUB_USER: qwe1
    - DOCKERHUB_PROJECT: dind-ansible-molecule
  #matrix:
  #  - whatever

before_script:
  - docker info

script:
  # test build 2.9
  - docker build -t 2.9 -f Dockerfile .
  - docker build -t 2.9-root -f Dockerfile-root .
  # test build 2.8
  - docker build -t 2.8 -f Dockerfile-2.8 .
  - docker build -t 2.8-root -f Dockerfile-2.8-root .
  # test build 2.7
  - docker build -t 2.7 -f Dockerfile-2.7 .
  - docker build -t 2.7-root -f Dockerfile-2.7-root .
  # run 2.9
  - docker run --rm 2.9 ansible --version
  - docker run --rm 2.9-root ansible --version
  # run 2.8
  - docker run --rm 2.8 ansible --version
  - docker run --rm 2.8-root ansible --version
  # run 2.7
  - docker run --rm 2.7 ansible --version
  - docker run --rm 2.7-root ansible --version