---
services: docker

env:
  global:
    - DOCKERHUB_USER: qwe1
    - DOCKERHUB_PROJECT: dind-ansible-molecule
  #matrix:
  #  - whatever

before_script:
  - docker info

script:
  # test 2.9
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root molecule --version
  # test 2.8
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8 ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8 molecule --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8-root ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.8-root molecule --version
  # test 2.7
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7 ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7 molecule --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7-root ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:2.7-root molecule --version
