---
services: docker

env:
  global:
    - DOCKERHUB_USER: qwe1
    - DOCKERHUB_PROJECT: dind-ansible-molecule
  #matrix:
  #  - whatever

before_script:
  - docker info

script:
  # test 2.9
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest molecule --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:root molecule --version
  # test 2.8
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28 molecule --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_28-root molecule --version
  # test 2.7
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27 molecule --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root ansible --version
  - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$ANSIBLE_VERSION_27-root molecule --version
